//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api.Models
{
    using System;
    
    public enum currentState : int
    {
        inAttesa = 0,
        PresoInCarico = 1,
        InLavorazione = 2,
        Spedito = 3,
        Annullato = 4,
        ErroreSubmit = 5,
        ErroreValorizza = 6,
        ErroreConfirm = 7,
        Postalizzato = 8
    }
}
