//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Names
    {
        public int id { get; set; }
        public string businessName { get; set; }
        public string name { get; set; }
        public string surname { get; set; }
        public string complementNames { get; set; }
        public string complementAddress { get; set; }
        public string dug { get; set; }
        public string address { get; set; }
        public string houseNumber { get; set; }
        public string cap { get; set; }
        public string city { get; set; }
        public string province { get; set; }
        public string state { get; set; }
        public System.DateTime insertDate { get; set; }
        public int currentState { get; set; }
        public bool valid { get; set; }
        public int operationId { get; set; }
        public string requestId { get; set; }
        public string orderId { get; set; }
        public string codice { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<decimal> vatPrice { get; set; }
        public Nullable<decimal> totalPrice { get; set; }
        public byte[] attachedFile { get; set; }
        public string fileName { get; set; }
        public Nullable<System.DateTime> presaInCaricoDate { get; set; }
        public Nullable<System.DateTime> consegnatoDate { get; set; }
        public string stato { get; set; }
        public string guidUser { get; set; }
        public Nullable<bool> tipoStampa { get; set; }
        public Nullable<bool> fronteRetro { get; set; }
        public Nullable<bool> ricevutaRitorno { get; set; }
        public bool locked { get; set; }
        public Nullable<System.Guid> reSendGuid { get; set; }
        public string fiscalCode { get; set; }
        public string mobile { get; set; }
    
        public virtual Operations Operations { get; set; }
    }
}
