//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api.Models
{
    using System;
    
    public enum operationType : int
    {
        ROL = 1,
        LOL = 2,
        TELEGRAMMA = 3,
        MOL = 4,
        COL = 5
    }
}
