//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api.Models
{
    using System;
    
    public enum products : int
    {
        CartoPlus10SC = 1,
        CartoPlusLGRidotto = 2,
        CartoPlusLG = 3,
        CartolinaA5 = 4,
        CartolinaA6 = 5
    }
}
